# -*- coding: utf-8 -*-
"""TAHAP 4-Solution Reuse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18V_7muhvbIka2Kwc8B61dCy2KKaITP2z
"""

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/My Drive/TA_PENALARAN_KOMPUTER/modelhtml.html'

from IPython.display import display, HTML

display(HTML(file_path))